-- 在 Supabase SQL Editor 執行一次。管理員帳號的建立步驟見 README。
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  username text not null unique check (username ~ '^[a-z0-9._-]{1,64}$'),
  role text not null check (role in ('admin', 'voter')),
  created_at timestamptz not null default now()
);

create table if not exists public.options (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 150),
  video_url text not null check (char_length(video_url) <= 2000 and video_url ~* '^https?://[^[:space:]]+$'),
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  option_id bigint not null references public.options(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists votes_option_id_idx on public.votes(option_id);

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.options enable row level security;
alter table public.votes enable row level security;

revoke all on public.profiles, public.options, public.votes from anon, authenticated;
grant select on public.profiles to authenticated;
grant select on public.options to anon, authenticated;
grant insert on public.options to authenticated;
grant select, insert on public.votes to authenticated;
grant usage on sequence public.options_id_seq to authenticated;

drop policy if exists "profiles_read_self_or_admin" on public.profiles;
create policy "profiles_read_self_or_admin" on public.profiles
for select to authenticated
using (id = (select auth.uid()) or (select public.is_admin()));

drop policy if exists "options_read_all" on public.options;
create policy "options_read_all" on public.options
for select to anon, authenticated using (true);

drop policy if exists "options_insert_admin" on public.options;
create policy "options_insert_admin" on public.options
for insert to authenticated with check ((select public.is_admin()));

drop policy if exists "votes_read_self_or_admin" on public.votes;
create policy "votes_read_self_or_admin" on public.votes
for select to authenticated
using (user_id = (select auth.uid()) or (select public.is_admin()));

drop policy if exists "votes_insert_once" on public.votes;
create policy "votes_insert_once" on public.votes
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'voter')
);

-- user_id 是 votes 的主鍵，所以資料庫會拒絕第二票；沒有更新與刪除投票的政策。
